packages:
  - "apps/*"
  - "packages/*"
  - "lcsp-python-workers/src/lcsp_workers/scanner/ts_js_bridge/ts-js-analyzer"
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  sharp: true
  unrs-resolver: true
