import {
  ASSESSMENT_RUNTIME_ENGINEERING_RULE_TOOL_PREFIXES,
  ASSESSMENT_RUNTIME_GATE_TOOL_NAMES,
} from "@lcsp/contracts/evidence";

export const ENGINEERING_RULE_ACTIVITY_TOOL_PREFIXES =
  ASSESSMENT_RUNTIME_ENGINEERING_RULE_TOOL_PREFIXES;

export const ENGINEERING_RULE_GATE_TOOL_NAME =
  ASSESSMENT_RUNTIME_GATE_TOOL_NAMES.engineeringRuleGate;
