#!/usr/bin/env bash
# Heavy W5 checks on fresh, migrated, disposable databases. No live model/provider calls.
set -uo pipefail
repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root" || exit 1
run_id="$(date -u +%Y%m%d_%H%M%S)_$$"
run_dir="$repo_root/reports/w5-regression/$run_id"
mkdir -p "$run_dir" || exit 1
postgres_container=lcsp-w5-disposable-postgres-55451
if ! docker inspect "$postgres_container" >/dev/null 2>&1; then
  docker run --detach --name "$postgres_container" --label lcsp.disposable=w5 --publish 127.0.0.1:55451:5432 --env POSTGRES_PASSWORD=postgres postgres:16 >/dev/null || exit 1
fi
if [[ "$(docker inspect "$postgres_container" --format '{{index .Config.Labels "lcsp.disposable"}}')" != w5 ]]; then
  printf 'Refusing a PostgreSQL container without the W5 disposable label.\n' >&2; exit 1
fi
docker start "$postgres_container" >/dev/null || exit 1
for attempt in {1..30}; do
  if docker exec "$postgres_container" pg_isready -U postgres -d postgres >/dev/null 2>&1; then break; fi
  sleep 1
done
docker exec "$postgres_container" pg_isready -U postgres -d postgres || exit 1
schema_database="lcsp_api_w5_schema_$run_id"
jest_database="lcsp_api_w5_jest_$run_id"
schema_url="postgresql://postgres:postgres@127.0.0.1:55451/$schema_database?schema=public"
jest_url="postgresql://postgres:postgres@127.0.0.1:55451/$jest_database?schema=public"
W5_SCHEMA_DATABASE="$schema_database" W5_JEST_DATABASE="$jest_database" node <<'NODE' || exit 1
const { createRequire } = require('node:module');
const { resolve } = require('node:path');
const { Client } = createRequire(resolve('apps/api/package.json'))('pg');
(async () => {
 const client = new Client({connectionString:'postgresql://postgres:postgres@127.0.0.1:55451/postgres'}); await client.connect();
 try { for(const name of [process.env.W5_SCHEMA_DATABASE, process.env.W5_JEST_DATABASE]) { if(!/^lcsp_api_w5_(schema|jest)_[0-9_]+$/.test(name)) throw Error('Invalid disposable database name'); await client.query(`CREATE DATABASE "${name}"`); console.log(`Created ${name}`); } } finally { await client.end(); }
})().catch(error=>{console.error(error.message); process.exitCode=1;});
NODE
export NODE_OPTIONS='--max-old-space-size=4096 --experimental-vm-modules'
export DATABASE_URL="$schema_url" PHASE25_DATABASE_URL="$jest_url" LCSP_W2_PG_PORT=55451
result=0
run_check() {
  local name="$1"; shift
  printf '\nRunning %s\n' "$name"
  "$@" > "$run_dir/$name.log" 2>&1
  local status=$?
  printf '%s\t%s\n' "$name" "$status" | tee -a "$run_dir/results.tsv"
  tail -n 20 "$run_dir/$name.log"
  if [[ $status != 0 ]]; then result=1; fi
}
run_check runtime-packages pnpm run build:runtime-packages
run_check schema-migrations env DATABASE_URL="$schema_url" pnpm --dir apps/api run prisma:migrate:deploy
run_check integration-migrations env DATABASE_URL="$jest_url" pnpm --dir apps/api run prisma:migrate:deploy
run_check api-build pnpm --dir apps/api run build
run_check web-route-types pnpm --dir apps/web exec next typegen
# Stale generated dev route validators are regenerated by next dev, not next typegen.
# An existing development server should be stopped before running this full check.
run_check typecheck pnpm run typecheck:run
run_check imports pnpm run check:imports
run_check contracts pnpm run check:contracts
run_check agentic-tools pnpm run check:agentic-tools
run_check retired-legal-authority pnpm run check:legal-v1-retired
run_check api-jest pnpm --dir apps/api exec jest --config ./jest.config.ts --runInBand --json --outputFile "$run_dir/api-jest-results.json"
run_check api-e2e pnpm --dir apps/api exec jest --config ./test/jest-e2e.ts --runInBand --json --outputFile "$run_dir/api-e2e-results.json"
run_check web pnpm run test:web:run
run_check root-python env PYTHONPATH="$repo_root/deepagents:$repo_root/deepagents/tests" "$repo_root/deepagents/.venv/bin/pytest" -q "$repo_root/deepagents/tests/test_assessment_root_agent.py" "$repo_root/deepagents/tests/test_assessment_researcher_isolation_fixtures.py" "$repo_root/deepagents/tests/test_native_researcher_capability_preparation.py" "$repo_root/deepagents/tests/test_native_researcher_task_preparation.py" "$repo_root/deepagents/tests/test_native_root_checkpoint_preparation.py" "$repo_root/deepagents/tests/test_graph_runtime_checkpoint.py" "$repo_root/deepagents/tests/test_runtime_control.py" "$repo_root/deepagents/tests/test_agent_server_client.py" "$repo_root/deepagents/tests/test_entrypoint.py" "$repo_root/deepagents/tests/test_worker_config_residue.py" "$repo_root/deepagents/tests/test_root_live_eval_budget.py"
run_check hitl-postgres node tests/assessment-hitl-vertical.mjs
run_check decisions-report-postgres node tests/assessment-domain-vertical.mjs
run_check diff-whitespace git diff --check
printf '\nW5 regression exit code: %s\nEvidence directory: %s\n' "$result" "$run_dir"
exit "$result"
