#!/usr/bin/env bash
# W6 gate (LCSP-356): heavy checks on fresh, migrated, DISPOSABLE databases. No live model/provider calls.
#
# The default cutover starts NO AI re-evaluation and spends NO credits: the rehearsal proves that on a
# populated copy, then drives the SEPARATE explicit re-evaluation phase (preflight, canary, real
# Assessment Root with a SCRIPTED model, verification, capped batch, failure isolation). Nothing here
# ever calls a model provider and nothing here touches a non-disposable database.
#
#   bash tests/run-w6-gate.sh            # everything
#   W6_SKIP=api-lint,web-lint bash tests/run-w6-gate.sh   # skip named stages (comma separated)
#
# It never touches a developer or shared database: every database it creates lives in a throw-away
# container that carries the `lcsp.disposable=w6` label, and the rehearsal refuses any database name
# that does not start with `lcsp_w6_`.
set -uo pipefail
repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root" || exit 1
run_id="$(date -u +%Y%m%d_%H%M%S)_$$"
run_dir="$repo_root/reports/w6-regression/$run_id"
mkdir -p "$run_dir" || exit 1

postgres_container=lcsp-w6-disposable-postgres-55461
if ! docker inspect "$postgres_container" >/dev/null 2>&1; then
  docker run --detach --name "$postgres_container" --label lcsp.disposable=w6 --publish 127.0.0.1:55461:5432 --env POSTGRES_PASSWORD=postgres postgres:16 >/dev/null || exit 1
fi
if [[ "$(docker inspect "$postgres_container" --format '{{index .Config.Labels "lcsp.disposable"}}')" != w6 ]]; then
  printf 'Refusing a PostgreSQL container without the W6 disposable label.\n' >&2; exit 1
fi
docker start "$postgres_container" >/dev/null || exit 1
for attempt in {1..30}; do
  if docker exec "$postgres_container" pg_isready -U postgres -d postgres >/dev/null 2>&1; then break; fi
  sleep 1
done
docker exec "$postgres_container" pg_isready -U postgres -d postgres || exit 1

schema_database="lcsp_w6_schema_$run_id"
jest_database="lcsp_w6_jest_$run_id"
schema_url="postgresql://postgres:postgres@127.0.0.1:55461/$schema_database?schema=public"
jest_url="postgresql://postgres:postgres@127.0.0.1:55461/$jest_database?schema=public"
W6_SCHEMA_DATABASE="$schema_database" W6_JEST_DATABASE="$jest_database" node <<'NODE' || exit 1
const { createRequire } = require('node:module');
const { resolve } = require('node:path');
const { Client } = createRequire(resolve('apps/api/package.json'))('pg');
(async () => {
 const client = new Client({connectionString:'postgresql://postgres:postgres@127.0.0.1:55461/postgres'}); await client.connect();
 try { for(const name of [process.env.W6_SCHEMA_DATABASE, process.env.W6_JEST_DATABASE]) { if(!/^lcsp_w6_(schema|jest)_[0-9_]+$/.test(name)) throw Error('Invalid disposable database name'); await client.query(`CREATE DATABASE "${name}"`); console.log(`Created ${name}`); } } finally { await client.end(); }
})().catch(error=>{console.error(error.message); process.exitCode=1;});
NODE

export NODE_OPTIONS='--max-old-space-size=4096 --experimental-vm-modules'
export DATABASE_URL="$schema_url" PHASE25_DATABASE_URL="$jest_url" LCSP_W2_PG_PORT=55461
result=0
skip=",${W6_SKIP:-},"
run_check() {
  local name="$1"; shift
  if [[ "$skip" == *",$name,"* ]]; then printf '\nSkipping %s (W6_SKIP)\n' "$name"; return; fi
  printf '\nRunning %s\n' "$name"
  "$@" > "$run_dir/$name.log" 2>&1
  local status=$?
  printf '%s\t%s\n' "$name" "$status" | tee -a "$run_dir/results.tsv"
  tail -n 20 "$run_dir/$name.log"
  if [[ $status != 0 ]]; then result=1; fi
}

# ---- build and clean install ---------------------------------------------------------------------
run_check runtime-packages pnpm run build:runtime-packages
run_check schema-migrations env DATABASE_URL="$schema_url" pnpm --dir apps/api run prisma:migrate:deploy
run_check integration-migrations env DATABASE_URL="$jest_url" pnpm --dir apps/api run prisma:migrate:deploy
run_check api-build pnpm --dir apps/api run build
run_check web-route-types pnpm --dir apps/web exec next typegen
# Stale generated dev route validators are regenerated by next dev, not next typegen.
# An existing development server should be stopped before running this full check.
run_check typecheck pnpm run typecheck:run

# ---- repository policy checks (the same ones the lint stage chains) -------------------------------
run_check imports pnpm run check:imports
run_check contracts pnpm run check:contracts
run_check agentic-tools pnpm run check:agentic-tools
run_check retired-legal-authority pnpm run check:legal-v1-retired
run_check api-lint pnpm --dir apps/api run lint
run_check web-lint pnpm --dir apps/web run lint

# ---- the W6 surface: routes, middleware, archive, tooling -----------------------------------------
run_check w6-surface env W6_PG_TEST_URL="$schema_url" pnpm --dir apps/api exec jest --config ./jest.config.ts --runInBand src/app.routes.spec.ts src/platform/http src/modules/legacy-archive src/modules/legacy-migration src/platform/outbox
run_check w6-web pnpm --dir apps/web exec tsx --tsconfig tsconfig.test.json --test --test-concurrency=1 tests/legacy-archive-report-row.test.ts tests/legacy-archive-bff.test.ts

# ---- full suites -------------------------------------------------------------------------------
run_check api-jest pnpm --dir apps/api exec jest --config ./jest.config.ts --runInBand --json --outputFile "$run_dir/api-jest-results.json"
run_check api-e2e pnpm --dir apps/api exec jest --config ./test/jest-e2e.ts --runInBand --json --outputFile "$run_dir/api-e2e-results.json"
run_check web pnpm run test:web:run
run_check python-all env PYTHONPATH="$repo_root/deepagents:$repo_root/deepagents/tests" "$repo_root/deepagents/.venv/bin/pytest" -q --no-header -p no:cacheprovider "$repo_root/deepagents/tests" --ignore="$repo_root/deepagents/tests/integration" --ignore="$repo_root/deepagents/tests/vertical"
run_check hitl-postgres node tests/assessment-hitl-vertical.mjs
run_check decisions-report-postgres node tests/assessment-domain-vertical.mjs

# ---- the cutover rehearsal on a production-shaped copy -------------------------------------------
run_check cutover-rehearsal env \
  W6_PG_PORT=55461 W6_PG_CONTAINER="$postgres_container" \
  W6_API_MAIN="$repo_root/apps/api/dist/src/main.js" \
  W6_CLI="$repo_root/apps/api/dist/src/modules/legacy-migration/presentation/cli/legacy-migration.cli.js" \
  node tests/w6-cutover-rehearsal.mjs --evidence-dir "$run_dir/rehearsal" --require-api

run_check diff-whitespace git diff --check
printf '\nW6 gate exit code: %s\nEvidence directory: %s\n' "$result" "$run_dir"
exit "$result"
