export const GITHUB_INTEGRATION_ERROR_CODES = {
  connectionNotFound: "CONNECTION_NOT_FOUND",
  invalidRedirectUri: "INVALID_REDIRECT_URI",
  githubStateInvalid: "GITHUB_STATE_INVALID",
  githubCallbackInvalid: "GITHUB_CALLBACK_INVALID",
  permissionsInsufficient: "PERMISSIONS_INSUFFICIENT",
  refNotResolvable: "REF_NOT_RESOLVABLE",
  refOutOfScope: "REF_OUT_OF_SCOPE",
  snapshotNotFound: "SNAPSHOT_NOT_FOUND",
  snapshotRetrievalFailed: "SNAPSHOT_RETRIEVAL_FAILED",
  assessmentStateInvalid: "ASSESSMENT_STATE_INVALID",
  scanBlockedMapping: "SCAN_BLOCKED_MAPPING",
  scanIdempotencyConflict: "IDEMPOTENCY_CONFLICT",
  scanIdempotencyKeyRequired: "IDEMPOTENCY_KEY_REQUIRED",
  scanTriggerSourceInvalid: "SCAN_TRIGGER_SOURCE_INVALID",
} as const;
