"""Canonical vocabulary for the repository-wide Program Evidence Graph."""
from __future__ import annotations

PROGRAM_GRAPH_SCHEMA_VERSION = "2.0.0"

NODE_TYPES = frozenset({
    "REPOSITORY", "FILE", "MODULE", "PACKAGE", "PACKAGE_DEPENDENCY",
    "CLASS", "INTERFACE", "FUNCTION", "METHOD", "PARAMETER", "RETURN_VALUE",
    "VARIABLE", "CONSTANT", "PROPERTY", "DTO", "DTO_FIELD", "TYPE", "CALL_SITE",
    "ASSIGNMENT", "BRANCH", "LOOP", "TRY_CATCH", "TRANSFORMATION", "PARSER",
    "VALIDATOR", "SERIALIZER", "HTTP_ROUTE", "HTTP_REQUEST", "HTTP_RESPONSE",
    "EVENT", "QUEUE", "COMMAND", "QUERY", "CRON", "WEBHOOK", "DATABASE",
    "TABLE", "ENTITY", "REPOSITORY_ACCESS", "CACHE", "FILE_STORAGE",
    "EXTERNAL_SERVICE", "EXTERNAL_API", "SDK_CLIENT", "AI_PROVIDER",
    "AI_MODEL_INVOCATION", "AI_INPUT", "AI_OUTPUT", "BUSINESS_ACTION",
    "STATUS_CHANGE", "APPROVAL", "REJECTION", "RANKING", "RECOMMENDATION",
    "NOTIFICATION", "HUMAN_REVIEW", "HUMAN_OVERRIDE", "DATA_CATEGORY",
    "PERSONAL_DATA", "SENSITIVE_DATA", "SECRET", "SOURCE_ANCHOR", "COVERAGE_GAP",
    "UNRESOLVED_DYNAMIC_TARGET",
})

EDGE_TYPES = frozenset({
    "CONTAINS", "DECLARES", "IMPORTS", "EXPORTS", "DEPENDS_ON", "RESOLVES_TO",
    "IMPLEMENTS", "EXTENDS", "CALLS", "CALLS_DYNAMICALLY", "CALLS_EXTERNAL",
    "HAS_PARAMETER", "PASSES_ARGUMENT", "RETURNS", "RECEIVES_RETURN",
    "DECLARES_VARIABLE", "ASSIGNS", "ALIASES", "READS", "WRITES",
    "READS_PROPERTY", "WRITES_PROPERTY", "MAPS_TO", "PARSES", "SERIALIZES",
    "DESERIALIZES", "CASTS_TO", "TRANSFORMS", "VALIDATES", "SANITIZES",
    "BRANCHES_ON", "LOOPS_OVER", "THROWS", "CATCHES", "CALLS_API", "HANDLED_BY",
    "PUBLISHES_EVENT", "CONSUMES_EVENT", "PUBLISHES_COMMAND", "HANDLES_COMMAND",
    "PUBLISHES_QUERY", "HANDLES_QUERY", "READS_FROM", "WRITES_TO", "PERSISTS_TO",
    "LOADS_FROM", "SENDS_TO_EXTERNAL", "RECEIVES_FROM_EXTERNAL", "SENDS_TO_AI",
    "RECEIVES_FROM_AI", "TRIGGERS", "AFFECTS", "APPROVES", "REJECTS", "RANKS",
    "RECOMMENDS", "UPDATES_STATUS", "REVIEWED_BY", "OVERRIDDEN_BY",
    "CONTAINS_DATA_CATEGORY", "CORROBORATES", "SUPPORTED_BY", "HAS_LIMITATION",
})

DATA_FLOW_EDGES = frozenset({
    "PASSES_ARGUMENT", "RETURNS", "RECEIVES_RETURN", "ASSIGNS", "ALIASES",
    "READS_PROPERTY", "WRITES_PROPERTY", "MAPS_TO", "PARSES", "SERIALIZES",
    "DESERIALIZES", "CASTS_TO", "TRANSFORMS", "VALIDATES", "SANITIZES",
    "READS_FROM", "WRITES_TO", "PERSISTS_TO", "LOADS_FROM", "SENDS_TO_EXTERNAL",
    "RECEIVES_FROM_EXTERNAL", "SENDS_TO_AI", "RECEIVES_FROM_AI",
})
DECISION_EDGE_TYPES = frozenset({
    "BRANCHES_ON", "TRIGGERS", "APPROVES", "REJECTS", "RANKS", "RECOMMENDS",
    "UPDATES_STATUS", "AFFECTS", "REVIEWED_BY", "OVERRIDDEN_BY",
})
HUMAN_CONTROL_NODE_TYPES = frozenset({"HUMAN_REVIEW", "HUMAN_OVERRIDE"})
BUSINESS_ACTION_NODE_TYPES = frozenset({
    "BUSINESS_ACTION", "STATUS_CHANGE", "APPROVAL", "REJECTION", "RANKING",
    "RECOMMENDATION", "NOTIFICATION",
})
