export const SCAN_ERROR_CODES = {
  jobNotFound: "SCAN_JOB_NOT_FOUND",
  jobWrongState: "SCAN_JOB_WRONG_STATE",
  evidenceSchemaInvalid: "EVIDENCE_SCHEMA_INVALID",
  privacyFlagsInvalid: "PRIVACY_FLAGS_INVALID",
  evidenceReportNotFound: "EVIDENCE_REPORT_NOT_FOUND",
  profileAlreadyExists: "PROFILE_ALREADY_EXISTS",
  technicalProfileSchemaInvalid: "SCHEMA_INVALID",
  technicalProfileNotFound: "TECHNICAL_PROFILE_NOT_FOUND",
  aiUsageFlowAlreadyExists: "FLOW_ALREADY_EXISTS",
  aiUsageFlowSchemaInvalid: "SCHEMA_INVALID",
  claimMissingEvidenceRef: "CLAIM_MISSING_EVIDENCE_REF",
  aiUsageFlowNotFound: "AI_USAGE_FLOW_NOT_FOUND",
  conflictSchemaInvalid: "SCHEMA_INVALID",
  conflictScoreInvalid: "CONFLICT_SCORE_INVALID",
  evidenceRefsEmpty: "EVIDENCE_REFS_EMPTY",
  conflictNotFound: "CONFLICT_NOT_FOUND",
  conflictAlreadyResolved: "CONFLICT_ALREADY_RESOLVED",
  dismissReasonRequired: "DISMISS_REASON_REQUIRED",
  pendingConflictsExist: "PENDING_CONFLICTS_EXIST",
  verifiedProfileSchemaInvalid: "SCHEMA_INVALID",
  verifiedProfileNotFound: "VERIFIED_PROFILE_NOT_FOUND",
  corpusVersionNotApproved: "CORPUS_VERSION_NOT_APPROVED",
  ruleCatalogVersionNotApproved: "RULE_CATALOG_VERSION_NOT_APPROVED",
  citationOutOfAllowlist: "CITATION_OUT_OF_ALLOWLIST",
  citationRepealed: "CITATION_REPEALED",
  legalRuleMatchSchemaInvalid: "SCHEMA_INVALID",
  legalRuleMatchNotFound: "LEGAL_RULE_MATCH_NOT_FOUND",
  resultAlreadyExists: "RESULT_ALREADY_EXISTS",
  classificationOverclaim: "CLASSIFICATION_OVERCLAIM",
  classificationSchemaInvalid: "SCHEMA_INVALID",
  classificationResultNotFound: "CLASSIFICATION_RESULT_NOT_FOUND",
} as const;

export type ScanErrorCode =
  (typeof SCAN_ERROR_CODES)[keyof typeof SCAN_ERROR_CODES];
