import { PDFDocument } from "pdf-lib";
import {
  ANSWER_STATES,
  READINESS_CLASSIFICATION_STATUSES,
  READINESS_EXPORT_ARTIFACT_TYPES,
  READINESS_EXPORT_BADGES,
  READINESS_EXPORT_LABELS,
  type ReadinessExportContent,
} from "@lcsp/contracts/wizard";

import {
  buildReadinessExportPdfDocument,
  ReadinessExportPdfService,
} from "./readiness-export-pdf.service.js";

describe("ReadinessExportPdfService", () => {
  const content = createContent();

  it("renders a valid PDF without mutating the persisted source content", async () => {
    const service = new ReadinessExportPdfService();
    const sourceBeforeRender = JSON.stringify(content);

    const bytes = await service.render(content);
    const document = await PDFDocument.load(bytes);

    expect(Buffer.from(bytes).subarray(0, 5).toString("ascii")).toBe("%PDF-");
    expect(document.getPageCount()).toBe(1);
    expect(document.getTitle()).toBe(
      READINESS_EXPORT_LABELS.wizardReadinessExport,
    );
    expect(JSON.stringify(content)).toBe(sourceBeforeRender);
  });

  it("builds every guarded readiness section from the persisted content", () => {
    const document = buildReadinessExportPdfDocument(content);

    expect(document.title).toBe(content.title);
    expect(document.badge).toBe(content.badge);
    expect(document.metadata).toEqual(
      expect.arrayContaining([
        `Assessment ID: ${content.metadata.assessment_id}`,
        `Export version: ${content.metadata.version}`,
        `Wizard profile version: ${content.metadata.wizard_profile_version}`,
        `Generated by: ${content.metadata.generated_by}`,
      ]),
    );
    expect(document.sections).toEqual([
      {
        heading: "Missing evidence",
        items: content.missing_evidence.map(
          (item) => `${item.label}: ${item.description}`,
        ),
      },
      {
        heading: "Information requiring verification",
        items: content.unresolved_unknown_items.map((item) => item.label),
      },
      {
        heading: "Preparation guidance",
        items: content.preparation_guidance,
      },
      { heading: "Next steps", items: content.next_steps },
    ]);
  });

  it("paginates long content and renders a neutral empty state", async () => {
    const service = new ReadinessExportPdfService();
    const longContent: ReadinessExportContent = {
      ...content,
      unresolved_unknown_items: [],
      missing_evidence: Array.from({ length: 90 }, (_, index) => ({
        type: `evidence-${index}`,
        label: `Evidence item ${index}`,
        description:
          "Provide the technical material needed to verify this readiness item before the next workflow gate.",
      })),
    };

    const documentModel = buildReadinessExportPdfDocument(longContent);
    const bytes = await service.render(longContent);
    const document = await PDFDocument.load(bytes);

    expect(
      documentModel.sections.find(
        (section) => section.heading === "Information requiring verification",
      )?.items,
    ).toEqual(["No items recorded."]);
    expect(document.getPageCount()).toBeGreaterThan(1);
  });
});

function createContent(): ReadinessExportContent {
  return {
    artifact_type: READINESS_EXPORT_ARTIFACT_TYPES.wizardReadinessExport,
    label: READINESS_EXPORT_LABELS.wizardReadinessExport,
    badge: READINESS_EXPORT_BADGES.readinessOnly,
    title: READINESS_EXPORT_LABELS.wizardReadinessExport,
    preview: "Preparation gaps that remain before the next evidence gate.",
    metadata: {
      artifact_type: READINESS_EXPORT_ARTIFACT_TYPES.wizardReadinessExport,
      label: READINESS_EXPORT_LABELS.wizardReadinessExport,
      readiness_only: true,
      classification_status:
        READINESS_CLASSIFICATION_STATUSES.lockedEvidenceRequired,
      wizard_profile_version: 3,
      assessment_id: "assessment-1",
      generated_by: "user-1",
      version: 2,
      generated_at: "2026-08-02T00:00:00.000Z",
    },
    missing_evidence: [
      {
        type: "technical_evidence",
        label: "Technical evidence",
        description: "Accepted technical evidence has not been produced yet.",
      },
    ],
    unresolved_unknown_items: [
      {
        question_id: "humanReview",
        label: "Human review requires verification",
        answer_state: ANSWER_STATES.explicitUnknown,
      },
    ],
    preparation_guidance: ["Connect the repository used by this system."],
    next_steps: ["Run the repository evidence workflow."],
  };
}
