import { Injectable } from "@nestjs/common";
import type { ReadinessExportContent } from "@lcsp/contracts/wizard";
import {
  PDFDocument,
  StandardFonts,
  type PDFFont,
  type PDFPage,
  rgb,
} from "pdf-lib";

const PAGE_SIZE = { width: 595.28, height: 841.89 } as const;
const PAGE_MARGIN = 50;
const CONTENT_WIDTH = PAGE_SIZE.width - PAGE_MARGIN * 2;
const BODY_FONT_SIZE = 10;
const BODY_LINE_HEIGHT = 15;
const EMPTY_SECTION_TEXT = "No items recorded.";

export interface ReadinessExportPdfSection {
  heading: string;
  items: string[];
}

export interface ReadinessExportPdfDocument {
  title: string;
  badge: string;
  preview: string;
  metadata: string[];
  sections: ReadinessExportPdfSection[];
}

export function buildReadinessExportPdfDocument(
  content: ReadinessExportContent,
): ReadinessExportPdfDocument {
  return {
    title: content.title,
    badge: content.badge,
    preview: content.preview,
    metadata: [
      `Artifact type: ${content.metadata.artifact_type}`,
      `Readiness only: ${String(content.metadata.readiness_only)}`,
      `Classification status: ${content.metadata.classification_status}`,
      `Assessment ID: ${content.metadata.assessment_id}`,
      `Export version: ${content.metadata.version}`,
      `Wizard profile version: ${content.metadata.wizard_profile_version}`,
      `Generated by: ${content.metadata.generated_by}`,
      `Generated at: ${content.metadata.generated_at}`,
    ],
    sections: [
      {
        heading: "Missing evidence",
        items: normalizeItems(
          content.missing_evidence.map(
            (item) => `${item.label}: ${item.description}`,
          ),
        ),
      },
      {
        heading: "Information requiring verification",
        items: normalizeItems(
          content.unresolved_unknown_items.map((item) => item.label),
        ),
      },
      {
        heading: "Preparation guidance",
        items: normalizeItems(content.preparation_guidance),
      },
      {
        heading: "Next steps",
        items: normalizeItems(content.next_steps),
      },
    ],
  };
}

@Injectable()
export class ReadinessExportPdfService {
  async render(content: ReadinessExportContent): Promise<Uint8Array> {
    const model = buildReadinessExportPdfDocument(content);
    const document = await PDFDocument.create();
    const regularFont = await document.embedFont(StandardFonts.Helvetica);
    const boldFont = await document.embedFont(StandardFonts.HelveticaBold);
    const writer = new PdfPageWriter(document, regularFont, boldFont);

    document.setTitle(model.title);
    document.setSubject(`${model.badge} readiness artifact`);
    document.setAuthor("LCSP");
    document.setCreator("LCSP Wizard Readiness Export");

    writer.drawTitle(model.title);
    writer.drawBadge(model.badge);
    writer.drawParagraph(model.preview, { spacingAfter: 14 });
    writer.drawMetadata(model.metadata);

    for (const section of model.sections) {
      writer.drawSection(section);
    }

    writer.drawPageNumbers();
    return document.save({ useObjectStreams: false });
  }
}

class PdfPageWriter {
  private page: PDFPage;
  private y: number;

  constructor(
    private readonly document: PDFDocument,
    private readonly regularFont: PDFFont,
    private readonly boldFont: PDFFont,
  ) {
    this.page = this.addPage();
    this.y = PAGE_SIZE.height - PAGE_MARGIN;
  }

  drawTitle(title: string): void {
    this.drawParagraph(title, {
      font: this.boldFont,
      fontSize: 20,
      lineHeight: 25,
      spacingAfter: 8,
    });
  }

  drawBadge(badge: string): void {
    this.drawParagraph(badge, {
      font: this.boldFont,
      fontSize: 9,
      lineHeight: 13,
      color: rgb(0.12, 0.32, 0.56),
      spacingAfter: 8,
    });
  }

  drawMetadata(items: string[]): void {
    this.ensureSpace(36);
    this.drawParagraph("Provenance", {
      font: this.boldFont,
      fontSize: 13,
      lineHeight: 18,
      spacingAfter: 4,
    });
    for (const item of items) {
      this.drawParagraph(item, {
        fontSize: 9,
        lineHeight: 13,
        spacingAfter: 1,
      });
    }
    this.y -= 12;
  }

  drawSection(section: ReadinessExportPdfSection): void {
    this.ensureSpace(54);
    this.drawParagraph(section.heading, {
      font: this.boldFont,
      fontSize: 13,
      lineHeight: 18,
      spacingAfter: 5,
    });
    for (const item of section.items) {
      this.drawParagraph(item, {
        prefix: "- ",
        indent: 12,
        spacingAfter: 5,
      });
    }
    this.y -= 8;
  }

  drawParagraph(
    text: string,
    options: {
      color?: ReturnType<typeof rgb>;
      font?: PDFFont;
      fontSize?: number;
      indent?: number;
      lineHeight?: number;
      prefix?: string;
      spacingAfter?: number;
    } = {},
  ): void {
    const font = options.font ?? this.regularFont;
    const fontSize = options.fontSize ?? BODY_FONT_SIZE;
    const lineHeight = options.lineHeight ?? BODY_LINE_HEIGHT;
    const indent = options.indent ?? 0;
    const prefix = options.prefix ?? "";
    const safeText = toWinAnsiText(text);
    const lines = wrapText(
      `${prefix}${safeText}`,
      font,
      fontSize,
      CONTENT_WIDTH - indent,
    );

    for (const line of lines) {
      this.ensureSpace(lineHeight);
      this.page.drawText(line, {
        x: PAGE_MARGIN + indent,
        y: this.y,
        size: fontSize,
        font,
        color: options.color ?? rgb(0.1, 0.13, 0.18),
      });
      this.y -= lineHeight;
    }
    this.y -= options.spacingAfter ?? 0;
  }

  drawPageNumbers(): void {
    const pages = this.document.getPages();
    for (const [index, page] of pages.entries()) {
      const label = `Page ${index + 1} of ${pages.length}`;
      page.drawText(label, {
        x:
          PAGE_SIZE.width -
          PAGE_MARGIN -
          this.regularFont.widthOfTextAtSize(label, 8),
        y: 24,
        size: 8,
        font: this.regularFont,
        color: rgb(0.38, 0.42, 0.49),
      });
    }
  }

  private ensureSpace(height: number): void {
    if (this.y - height >= PAGE_MARGIN) return;
    this.page = this.addPage();
    this.y = PAGE_SIZE.height - PAGE_MARGIN;
  }

  private addPage(): PDFPage {
    return this.document.addPage([PAGE_SIZE.width, PAGE_SIZE.height]);
  }
}

function normalizeItems(items: string[]): string[] {
  return items.length > 0 ? [...items] : [EMPTY_SECTION_TEXT];
}

function wrapText(
  text: string,
  font: PDFFont,
  fontSize: number,
  maxWidth: number,
): string[] {
  const words = text.split(/\s+/).filter(Boolean);
  if (words.length === 0) return [EMPTY_SECTION_TEXT];

  const lines: string[] = [];
  let line = "";
  for (const word of words) {
    const candidate = line.length === 0 ? word : `${line} ${word}`;
    if (font.widthOfTextAtSize(candidate, fontSize) <= maxWidth) {
      line = candidate;
      continue;
    }

    if (line.length > 0) lines.push(line);
    const segments = splitLongWord(word, font, fontSize, maxWidth);
    lines.push(...segments.slice(0, -1));
    line = segments.at(-1) ?? "";
  }
  if (line.length > 0) lines.push(line);
  return lines;
}

function splitLongWord(
  word: string,
  font: PDFFont,
  fontSize: number,
  maxWidth: number,
): string[] {
  if (font.widthOfTextAtSize(word, fontSize) <= maxWidth) return [word];

  const segments: string[] = [];
  let segment = "";
  for (const character of word) {
    const candidate = `${segment}${character}`;
    if (
      segment.length > 0 &&
      font.widthOfTextAtSize(candidate, fontSize) > maxWidth
    ) {
      segments.push(segment);
      segment = character;
    } else {
      segment = candidate;
    }
  }
  if (segment.length > 0) segments.push(segment);
  return segments;
}

function toWinAnsiText(value: string): string {
  return value
    .replace(/[\r\n\t]+/g, " ")
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^\x20-\x7e\xa0-\xff]/g, "?");
}
