import { ASSESSMENT_ACTIONS } from "../assessment/actions.ts";
import { DOCUMENT_ACTIONS } from "../document/actions.ts";

export const PBAC_ACTIONS = {
  assessmentCreate: ASSESSMENT_ACTIONS.create,
  assessmentList: "assessment:list",
  assessmentRead: "assessment:read",
  assessmentSettingsManage: "assessment:settings:manage",
  auditExport: "audit:export",
  auditRead: "audit:read",
  classificationRun: "classification:run",
  complianceDossierExport: "compliance-dossier:export",
  conflictFinalize: "conflict:finalize",
  conflictRead: "conflict:read",
  conflictResolve: "conflict:resolve",
  evidenceRead: "evidence:read",
  evidenceReadRedacted: "evidence:read:redacted",
  finalReportGenerate: "final-report:generate",
  documentGenerate: DOCUMENT_ACTIONS.generate,
  documentRead: DOCUMENT_ACTIONS.read,
  documentReadRedacted: DOCUMENT_ACTIONS.readRedacted,
  githubConnect: "github:connect",
  inviteDeveloper: "invite:developer",
  legalRuleCatalogAuthor: "legal-rule-catalog:author",
  legalRuleCatalogApprove: "legal-rule-catalog:approve",
  legalCorpusIngest: "legal-corpus:ingest",
  legalCorpusApprove: "legal-corpus:approve",
  legalCorpusRead: "legal-corpus:read",
  legalRuleMatchRead: "legal-rule-match:read",
  legalCitationValidate: "legal-citation:validate",
  classificationBaselineRead: "classification-baseline:read",
  classificationProposalValidate: "classification-proposal:validate",
  gapMatrixEvaluate: "gap-matrix:evaluate",
  gapEvidenceTraceRead: "gap-evidence-trace:read",
  classificationReviewSubmit: "classification-review:submit",
  managerDecisionChange: "manager-decision:change",
  membershipRevoke: "membership:revoke",
  metadataCheck: "pbac:metadata",
  outboxReplay: "outbox:replay",
  sessionVerify: "session:verify",
  scanRead: "scan:read",
  scanTrigger: "scan:trigger",
  technicalEvidenceReanalyze: "technical-evidence:reanalyze",
  snapshotCreate: "snapshot:create",
  verifiedProfileApprove: "verified-profile:approve",
  verifiedProfilePersist: "verified-profile:persist",
  verifiedProfileRead: "verified-profile:read",
  wizardWrite: "wizard:write",
  wizardSubmit: "wizard:submit",
  wizardExport: "wizard:export",
  workspaceRead: "workspace:read",
} as const;

export type PbacAction = (typeof PBAC_ACTIONS)[keyof typeof PBAC_ACTIONS];
