export const BILLING_PROVIDER = { sepay: "SEPAY" } as const;
export const BILLING_RECONCILIATION_EVENT_TYPES = {
  sepayWebhookAccepted: "command.billing.sepay-reconcile.v1",
} as const;

export const BILLING_RECONCILIATION_QUEUE_NAMES = {
  sepayWebhookAccepted: "lcsp.billing-sepay-reconcile.v1",
} as const;

/**
 * SePay HMAC-SHA256 webhook contract documented at
 * https://developer.sepay.vn/en/sepay-webhooks/xac-thuc.
 * The fixture below is a governed interoperability vector: its signature is
 * intentionally fixed rather than generated by the application under test.
 */
export const SEPAY_HMAC_CONTRACT = {
  algorithm: "HMAC-SHA256",
  signatureHeader: "X-SePay-Signature",
  timestampHeader: "X-SePay-Timestamp",
  signaturePrefix: "sha256=",
  signedMessageFormat: "{timestamp}.{raw_body}",
} as const;

export const SEPAY_HMAC_FIXTURE = {
  secret: "sepay-official-fixture-secret",
  timestamp: "1700000000",
  rawBody:
    '{ "id":"TX-FIXTURE-1", "transferAmount":"100000", "transferType":"in", "code":"LCSPFIXTURE", "description":"Nạp tiền đã test" }',
  signature:
    "sha256=15e78798d5dc0dae1fcfcca1edcaf29c3c71b6f54bdf8a6cd882ca83ec7c5495",
} as const;

export const BILLING_RECONCILIATION_ERROR_CODES = {
  invalidSignature: "BILLING_WEBHOOK_SIGNATURE_INVALID",
  staleTimestamp: "BILLING_WEBHOOK_TIMESTAMP_STALE",
  malformedBody: "BILLING_WEBHOOK_BODY_MALFORMED",
  invalidPayload: "BILLING_WEBHOOK_PAYLOAD_INVALID",
} as const;

export type SePayNormalizedPayload = {
  providerTransactionId: string;
  paymentCode: string | null;
  amountMinorUnits: bigint;
  transferDirection: "IN" | "OUT" | "UNKNOWN";
  referenceCode: string | null;
  transactionDate: string | null;
  integrityHash: string;
};
