export const BILLING_ORDER_STATUSES = {
  PENDING_PAYMENT: "PENDING_PAYMENT",
  CREDITED: "CREDITED",
  EXPIRED: "EXPIRED",
  CANCELLED: "CANCELLED",
  PENDING_RECONCILIATION: "PENDING_RECONCILIATION",
} as const;

export type BillingOrderStatus =
  (typeof BILLING_ORDER_STATUSES)[keyof typeof BILLING_ORDER_STATUSES];

export const PAYMENT_RECONCILIATION_STATUSES = {
  MATCHED: "MATCHED",
  UNMATCHED: "UNMATCHED",
  AMOUNT_MISMATCH: "AMOUNT_MISMATCH",
  DUPLICATE: "DUPLICATE",
  REJECTED: "REJECTED",
  NEEDS_REVIEW: "NEEDS_REVIEW",
} as const;

export type PaymentReconciliationStatus =
  (typeof PAYMENT_RECONCILIATION_STATUSES)[keyof typeof PAYMENT_RECONCILIATION_STATUSES];

export const PAYMENT_RECONCILIATION_REASONS = {
  INBOUND_REQUIRED: "INBOUND_REQUIRED",
  UNMATCHED_PAYMENT_CODE: "UNMATCHED_PAYMENT_CODE",
  AMBIGUOUS_ORDER_MATCH: "AMBIGUOUS_ORDER_MATCH",
  UNDERPAYMENT: "UNDERPAYMENT",
  OVERPAYMENT: "OVERPAYMENT",
  EXPIRED_ORDER: "EXPIRED_ORDER",
  OWNERSHIP_CONFLICT: "OWNERSHIP_CONFLICT",
  RECOVERABLE_EXCEPTION: "RECOVERABLE_EXCEPTION",
  DUPLICATE_PROVIDER_TRANSACTION: "DUPLICATE_PROVIDER_TRANSACTION",
} as const;

export type PaymentReconciliationReason =
  (typeof PAYMENT_RECONCILIATION_REASONS)[keyof typeof PAYMENT_RECONCILIATION_REASONS];

export const BILLING_RECONCILIATION_ACTIONS = {
  SETTLE: "SETTLE",
  REJECT: "REJECT",
} as const;

export type BillingReconciliationAction =
  (typeof BILLING_RECONCILIATION_ACTIONS)[keyof typeof BILLING_RECONCILIATION_ACTIONS];

export const BILLING_RECONCILIATION_RESULTS = {
  accepted: "ACCEPTED",
  rejected: "REJECTED",
} as const;

export type BillingReconciliationResult =
  (typeof BILLING_RECONCILIATION_RESULTS)[keyof typeof BILLING_RECONCILIATION_RESULTS];

export const BILLING_RESERVATION_STATUSES = {
  RESERVED: "RESERVED",
  SETTLED: "SETTLED",
  RELEASED: "RELEASED",
} as const;

export type BillingReservationStatus =
  (typeof BILLING_RESERVATION_STATUSES)[keyof typeof BILLING_RESERVATION_STATUSES];
