export const BILLING_ORDER_STATUSES = {
  PENDING_PAYMENT: "PENDING_PAYMENT",
  CREDITED: "CREDITED",
  EXPIRED: "EXPIRED",
  CANCELLED: "CANCELLED",
  PENDING_RECONCILIATION: "PENDING_RECONCILIATION",
} as const;

export type BillingOrderStatus =
  (typeof BILLING_ORDER_STATUSES)[keyof typeof BILLING_ORDER_STATUSES];

export const PAYMENT_RECONCILIATION_STATUSES = {
  MATCHED: "MATCHED",
  UNMATCHED: "UNMATCHED",
  AMOUNT_MISMATCH: "AMOUNT_MISMATCH",
  DUPLICATE: "DUPLICATE",
  REJECTED: "REJECTED",
  NEEDS_REVIEW: "NEEDS_REVIEW",
} as const;

export type PaymentReconciliationStatus =
  (typeof PAYMENT_RECONCILIATION_STATUSES)[keyof typeof PAYMENT_RECONCILIATION_STATUSES];

export const BILLING_RESERVATION_STATUSES = {
  RESERVED: "RESERVED",
  SETTLED: "SETTLED",
  RELEASED: "RELEASED",
} as const;

export type BillingReservationStatus =
  (typeof BILLING_RESERVATION_STATUSES)[keyof typeof BILLING_RESERVATION_STATUSES];
