from __future__ import annotations


AI_RULE_TABLE = [
    {
        "rule_id": "py-openai-chat-completions",
        "package": "openai",
        "pattern": [
            "ChatCompletion.create",
            "client.chat.completions.create",
            "openai.chat.completions.create",
        ],
        "finding_type": "AI_PROVIDER_USAGE",
        "base_confidence": 0.90,
    },
    {
        "rule_id": "py-openai-embeddings",
        "package": "openai",
        "pattern": ["Embedding.create", "client.embeddings.create"],
        "finding_type": "AI_PROVIDER_USAGE",
        "base_confidence": 0.90,
    },
    {
        "rule_id": "py-openai-responses",
        "package": "openai",
        "pattern": ["client.responses.create"],
        "finding_type": "AI_PROVIDER_USAGE",
        "base_confidence": 0.90,
    },
    {
        "rule_id": "py-openai-model-kwarg",
        "package": "openai",
        "pattern": ["model"],
        "finding_type": "AI_MODEL_INVOCATION",
        "base_confidence": 0.75,
    },
    {
        "rule_id": "py-anthropic-messages",
        "package": "anthropic",
        "pattern": ["client.messages.create", "Anthropic.messages.create"],
        "finding_type": "AI_PROVIDER_USAGE",
        "base_confidence": 0.90,
    },
    {
        "rule_id": "py-anthropic-model-kwarg",
        "package": "anthropic",
        "pattern": ["model"],
        "finding_type": "AI_MODEL_INVOCATION",
        "base_confidence": 0.85,
    },
    {
        "rule_id": "py-google-genai-generate",
        "package": "google.generativeai",
        "pattern": ["model.generate_content", "GenerativeModel", "genai.GenerativeModel"],
        "finding_type": "AI_PROVIDER_USAGE",
        "base_confidence": 0.90,
    },
    {
        "rule_id": "py-vertexai-predict",
        "package": "vertexai",
        "pattern": ["model.predict", "endpoint.predict", "vertexai.preview"],
        "finding_type": "AI_PROVIDER_USAGE",
        "base_confidence": 0.85,
    },
    {
        "rule_id": "py-hf-pipeline",
        "package": "transformers",
        "pattern": ["pipeline", "AutoModelFor", "AutoTokenizer", "Trainer"],
        "finding_type": "AI_FRAMEWORK_USAGE",
        "base_confidence": 0.80,
    },
    {
        "rule_id": "py-hf-inference",
        "package": "huggingface_hub",
        "pattern": ["InferenceClient", "HfApi", "inference_api"],
        "finding_type": "AI_PROVIDER_USAGE",
        "base_confidence": 0.80,
    },
    {
        "rule_id": "py-langchain-llm",
        "package": "langchain",
        "pattern": ["ChatOpenAI", "ChatAnthropic", "ChatGoogleGenerativeAI", "LLMChain", "chain.invoke", "chain.run", "chain.stream"],
        "finding_type": "AI_FRAMEWORK_USAGE",
        "base_confidence": 0.85,
    },
    {
        "rule_id": "py-langchain-agent",
        "package": "langchain",
        "pattern": ["AgentExecutor", "create_react_agent", "create_openai_functions_agent", "agent.run", "agent.invoke"],
        "finding_type": "AI_DECISION_FLOW_SIGNAL",
        "base_confidence": 0.75,
    },
    {
        "rule_id": "py-langchain-prompt",
        "package": "langchain",
        "pattern": ["PromptTemplate", "ChatPromptTemplate", "SystemMessagePromptTemplate", "HumanMessagePromptTemplate"],
        "finding_type": "SYSTEM_PROMPT_DETECTED",
        "base_confidence": 0.80,
    },
    {
        "rule_id": "py-langchain-rag",
        "package": "langchain",
        "pattern": ["VectorStoreRetriever", "RetrievalQA", "RAGChain", "retriever.invoke"],
        "finding_type": "RAG_USAGE_SIGNAL",
        "base_confidence": 0.85,
    },
    {
        "rule_id": "py-langchain-output-parser",
        "package": "langchain",
        "pattern": ["PydanticOutputParser", "JsonOutputParser", "StrOutputParser", "CommaSeparatedListOutputParser"],
        "finding_type": "MODEL_OUTPUT_PARSER_SIGNAL",
        "base_confidence": 0.80,
    },
    {
        "rule_id": "py-llamaindex-query",
        "package": "llama_index",
        "pattern": ["QueryEngine", "VectorStoreIndex", "index.as_query_engine", "query_engine.query", "as_query_engine.query"],
        "finding_type": "RAG_USAGE_SIGNAL",
        "base_confidence": 0.85,
    },
    {
        "rule_id": "py-llamaindex-llm",
        "package": "llama_index",
        "pattern": ["OpenAI", "Anthropic", "llm.complete", "llm.chat", "llm.stream_chat"],
        "finding_type": "AI_PROVIDER_USAGE",
        "base_confidence": 0.80,
    },
    {
        "rule_id": "py-sklearn-predict",
        "package": "sklearn",
        "pattern": ["model.predict", "clf.predict", "estimator.predict"],
        "finding_type": "AI_PROVIDER_USAGE",
        "base_confidence": 0.65,
    },
    {
        "rule_id": "py-sklearn-decision",
        "package": "sklearn",
        "pattern": ["model.predict_proba", "model.decision_function"],
        "finding_type": "AUTOMATED_DECISION_SIGNAL",
        "base_confidence": 0.60,
    },
    {
        "rule_id": "py-tf-predict",
        "package": "tensorflow",
        "pattern": ["model.predict", "model.call"],
        "finding_type": "AI_PROVIDER_USAGE",
        "base_confidence": 0.70,
    },
    {
        "rule_id": "py-keras-model",
        "package": "keras",
        "pattern": ["Sequential", "Model", "model.fit", "model.predict"],
        "finding_type": "AI_FRAMEWORK_USAGE",
        "base_confidence": 0.70,
    },
    {
        "rule_id": "py-torch-forward",
        "package": "torch",
        "pattern": ["model.forward", "torch.no_grad"],
        "finding_type": "AI_PROVIDER_USAGE",
        "base_confidence": 0.65,
    },
    {
        "rule_id": "py-local-http-inference",
        "package": "requests",
        "pattern": ["localhost:11434", "localhost:8080/v1", "/v1/chat/completions", "/api/generate", "ollama", "vllm", "llama.cpp"],
        "finding_type": "AI_PROVIDER_USAGE",
        "base_confidence": 0.75,
    },
    {
        "rule_id": "py-generic-predict",
        "package": "*",
        "pattern": [".predict", ".generate", ".infer", ".classify", ".score"],
        "finding_type": "AI_PROVIDER_USAGE",
        "base_confidence": 0.40,
    },
    {
        "rule_id": "py-system-prompt-variable",
        "package": "*",
        "pattern": ["system_prompt", "SYSTEM_PROMPT", "system_message", "SystemMessage"],
        "finding_type": "SYSTEM_PROMPT_DETECTED",
        "base_confidence": 0.70,
    },
    {
        "rule_id": "py-dynamic-prompt-ref",
        "package": "*",
        "pattern": ["format_map", "Template", "render"],
        "finding_type": "DYNAMIC_SYSTEM_PROMPT_REFERENCE",
        "base_confidence": 0.65,
    },
    {
        "rule_id": "py-pii-param",
        "package": "*",
        "pattern": ["user_data", "personal_data", "pii", "ssn", "dob"],
        "finding_type": "SENSITIVE_DATA_SIGNAL",
        "base_confidence": 0.55,
    },
]

