from __future__ import annotations


AI_PROVIDER_USAGE = "AI_PROVIDER_USAGE"
AI_FRAMEWORK_USAGE = "AI_FRAMEWORK_USAGE"
AI_MODEL_INVOCATION = "AI_MODEL_INVOCATION"
AI_INPUT_SIGNAL = "AI_INPUT_SIGNAL"
AI_OUTPUT_SIGNAL = "AI_OUTPUT_SIGNAL"
AI_DECISION_FLOW_SIGNAL = "AI_DECISION_FLOW_SIGNAL"
AUTOMATED_DECISION_SIGNAL = "AUTOMATED_DECISION_SIGNAL"
HUMAN_REVIEW_SIGNAL = "HUMAN_REVIEW_SIGNAL"
RANKING_SIGNAL = "RANKING_SIGNAL"
RECOMMENDATION_SIGNAL = "RECOMMENDATION_SIGNAL"
STATUS_UPDATE_SIGNAL = "STATUS_UPDATE_SIGNAL"
USER_IMPACT_SIGNAL = "USER_IMPACT_SIGNAL"
SENSITIVE_DATA_SIGNAL = "SENSITIVE_DATA_SIGNAL"
DOMAIN_CONTEXT_SIGNAL = "DOMAIN_CONTEXT_SIGNAL"
HARM_POTENTIAL_SIGNAL = "HARM_POTENTIAL_SIGNAL"
SYSTEM_PROMPT_DETECTED = "SYSTEM_PROMPT_DETECTED"
DYNAMIC_SYSTEM_PROMPT_REFERENCE = "DYNAMIC_SYSTEM_PROMPT_REFERENCE"
RAG_USAGE_SIGNAL = "RAG_USAGE_SIGNAL"
MODEL_OUTPUT_PARSER_SIGNAL = "MODEL_OUTPUT_PARSER_SIGNAL"
DISPLAY_ONLY_SIGNAL = "DISPLAY_ONLY_SIGNAL"
HUMAN_OVERSIGHT_CONTROL_SIGNAL = "HUMAN_OVERSIGHT_CONTROL_SIGNAL"
AI_INTERACTION_DISCLOSURE_SIGNAL = "AI_INTERACTION_DISCLOSURE_SIGNAL"
INCIDENT_HANDLING_SIGNAL = "INCIDENT_HANDLING_SIGNAL"
SCAN_COVERAGE_LIMITATION = "SCAN_COVERAGE_LIMITATION"
UNSUPPORTED_DYNAMIC_FLOW = "UNSUPPORTED_DYNAMIC_FLOW"

FINDING_TYPES: dict[str, dict[str, float]] = {
    AI_PROVIDER_USAGE: {"base_confidence": 0.35},
    AI_FRAMEWORK_USAGE: {"base_confidence": 0.35},
    AI_MODEL_INVOCATION: {"base_confidence": 0.70},
    AI_INPUT_SIGNAL: {"base_confidence": 0.55},
    AI_OUTPUT_SIGNAL: {"base_confidence": 0.55},
    AI_DECISION_FLOW_SIGNAL: {"base_confidence": 0.65},
    AUTOMATED_DECISION_SIGNAL: {"base_confidence": 0.75},
    HUMAN_REVIEW_SIGNAL: {"base_confidence": 0.70},
    RANKING_SIGNAL: {"base_confidence": 0.60},
    RECOMMENDATION_SIGNAL: {"base_confidence": 0.60},
    STATUS_UPDATE_SIGNAL: {"base_confidence": 0.65},
    USER_IMPACT_SIGNAL: {"base_confidence": 0.60},
    SENSITIVE_DATA_SIGNAL: {"base_confidence": 0.60},
    DOMAIN_CONTEXT_SIGNAL: {"base_confidence": 0.50},
    HARM_POTENTIAL_SIGNAL: {"base_confidence": 0.55},
    SYSTEM_PROMPT_DETECTED: {"base_confidence": 0.70},
    DYNAMIC_SYSTEM_PROMPT_REFERENCE: {"base_confidence": 0.65},
    RAG_USAGE_SIGNAL: {"base_confidence": 0.65},
    MODEL_OUTPUT_PARSER_SIGNAL: {"base_confidence": 0.65},
    DISPLAY_ONLY_SIGNAL: {"base_confidence": 0.55},
    HUMAN_OVERSIGHT_CONTROL_SIGNAL: {"base_confidence": 0.75},
    AI_INTERACTION_DISCLOSURE_SIGNAL: {"base_confidence": 0.65},
    INCIDENT_HANDLING_SIGNAL: {"base_confidence": 0.60},
    SCAN_COVERAGE_LIMITATION: {"base_confidence": 1.00},
    UNSUPPORTED_DYNAMIC_FLOW: {"base_confidence": 1.00},
}

CANONICAL_FINDING_TYPES = tuple(FINDING_TYPES.keys())


def is_canonical_finding_type(value: str) -> bool:
    return value in FINDING_TYPES
